version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Create pull requests for version updates
    open-pull-requests-limit: 10
    # Apply labels to pull requests
    labels:
      - "dependencies"
      - "javascript"
    # Group updates by dependency name
    versioning-strategy: "increase"
